name: bfban
description: bfban.com
publish_to: 'none'
version: '0.2.7'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.1
  cupertino_icons: ^1.0.2

  # 时间选择器 https://pub.dev/packages/syncfusion_flutter_datepicker
  syncfusion_flutter_datepicker: any

  # 请求模块 https://pub.dev/packages/dio
  dio: ^4.0.6

  # Dio Cookie 管理器 https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^2.0.0

  # 旧项目 https://pub.dev/packages/dio_http_cache
  # Dio 请求缓存 https://pub.dev/packages/dio_http_cache_lts
  dio_http_cache_lts: ^0.4.1

  # 状态管理 https://pub.dev/packages/provider
  provider: ^6.0.2

  # 路由管理 https://pub.dev/packages/fluro
  fluro: ^2.0.3

  # 包信息  https://pub.dev/packages/package_info_plus
  package_info_plus: ^4.1.0

  # html https://pub.dev/packages/flutter_html
  flutter_html: ^3.0.0-beta.2

  # svg渲染模块 https://pub.dev/packages/flutter_svg
  flutter_svg: any

  # 数据储存 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.6

  # 数据储存监听 https://pub.flutter-io.cn/packages/streaming_shared_preferences
  streaming_shared_preferences: ^2.0.0

  # 链接 https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.1.10

  # (图像or文件)选择器 https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^0.8.1
  image: any

  # 图片扩展(裁剪) https://pub.flutter-io.cn/packages/extended_image
  extended_image: ^8.1.0

  # 权限 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^10.0.2

  # link https://pub.flutter-io.cn/packages/app_links
  app_links: ^3.4.2

  # 网络状态 https://pub.flutter-io.cn/packages/connectivity_plus
  connectivity_plus: 3.0.3

  # 本地通知x消息 https://pub.flutter-io.cn/packages/flutter_local_notifications
  flutter_local_notifications: ^11.0.1

  # 相机(扫码 and 拍摄) https://pub.flutter-io.cn/packages/camerawesome
  camerawesome: ^2.0.0-dev.1

  # https://pub.flutter-io.cn/packages/quill_html_editor
  # quill_html_editor: ^2.1.8

  # 富文本扩展
  flutter_rte: any

  # uuid https://github.com/Daegalus/dart-uuid
  uuid: ^3.0.4

  # 多国语言 https://github.com/Daegalus/flutter_translate
  # https://www.unicode.org/reports/tr35/#Unicode_language_identifier
  flutter_translate: ^4.0.3
  flutter_i18n: ^0.34.0

  # 图片保存 https://pub.dev/packages/image_gallery_saver
  image_gallery_saver: ^2.0.0

  # 哨兵 https://pub.dev/packages/sentry
  sentry: ^7.9.0

  # UI库
  flutter_elui_plugin:
    path: ../flutter_elui_plugin

  # 视频 https://pub.flutter-io.cn/packages/video_player
  video_player: ^2.1.1

  # 动画
  animations: ^2.0.7

  # 极光 https://pub.flutter-io.cn/packages/jpush_flutter
  # 需要配置android/ios目录
  #  jpush_flutter: ^2.3.8

  # 许可证页 https://pub.flutter-io.cn/packages/flutter_custom_license_page
  flutter_custom_license_page: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.3.0
  flutter_lints: ^2.0.1

  # 启动屏幕 https://pub.flutter-io.cn/packages/flutter_native_splash
  flutter_native_splash: ^2.2.10+1
  build_runner: ^2.4.6

flutter_native_splash:
  color: "#2E4E81"
  branding: assets/splash/ic_launcher.png
  image: assets/splash/splash_center_logo.png
  branding_mode: center
  android_gravity: center
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/video/
    - assets/images/
    - assets/images/recordPlatforms/
    - assets/images/games/bf1/
    - assets/images/games/bf6/
    - assets/images/games/bfv/
    - assets/splash/